CREATE TABLE IF NOT EXISTS vehicles (
    id SERIAL PRIMARY KEY,
    plate VARCHAR(10) UNIQUE NOT NULL,
    vin VARCHAR(32),
    make VARCHAR(50),
    model VARCHAR(100),
    variant VARCHAR(100),
    year INT,
    body_type VARCHAR(50),
    fuel_type VARCHAR(20),
    engine_code VARCHAR(50),
    engine_displacement_l NUMERIC(3,1),
    engine_power_hp INT,
    engine_torque_nm INT,
    gearbox_type VARCHAR(50),
    gearbox_gears INT,
    drivetrain_type VARCHAR(20),
    rear_diff_lock BOOLEAN DEFAULT FALSE,
    center_diff_lock BOOLEAN DEFAULT FALSE,
    is_4x4 BOOLEAN DEFAULT FALSE,
    length_mm INT,
    width_mm INT,
    height_m NUMERIC(3,2),
    clearance_mm INT,
    curb_weight_kg INT,
    gross_weight_kg INT,
    seats INT,
    color VARCHAR(30),
    imported BOOLEAN DEFAULT FALSE,
    first_registration DATE,
    country_origin VARCHAR(50),
    owner_count INT,
    mileage_latest INT,
    mileage_updated_at TIMESTAMP,
    tax_per_year INT,
    co2_emission INT,
    euro_standard VARCHAR(10),
    raw_source_json JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vehicles_plate ON vehicles(plate);
CREATE INDEX IF NOT EXISTS idx_vehicles_vin ON vehicles(vin);
